//////////////////////////////////////////////////////////////////////////////
//                                                                          //
//                _  _          _            _                     _        //
//      __ _   __| || |__      | |__    ___ | | _ __    ___  _ __ | |__     //
//     / _` | / _` || '_ \     | '_ \  / _ \| || '_ \  / _ \| '__|| '_ \    //
//    | (_| || (_| || |_) |    | | | ||  __/| || |_) ||  __/| | _ | | | |   //
//     \__, | \__,_||_.__/_____|_| |_| \___||_|| .__/  \___||_|(_)|_| |_|   //
//     |___/             |_____|               |_|                          //
//                                                                          //
//////////////////////////////////////////////////////////////////////////////

/*****************************************************************************

    X11workbench - X11 programmer's 'work bench' application and toolkit
    Copyright (c) 2010-2018 by Bob Frazier (aka 'Big Bad Bombastic Bob')
                             all rights reserved

  DISCLAIMER:  The X11workbench application and toolkit software are supplied
               'as-is', with no warranties, either implied or explicit.
               Any claims to alleged functionality or features should be
               considered 'preliminary', and might not function as advertised.

  BSD-like license:

  There is no restriction as to what you can do with this software, so long
  as you include the above copyright notice and DISCLAIMER for any distributed
  work that is equal to or derived from this one, along with this paragraph
  that explains the terms of the license if the source is also being made
  available.  A "derived work" describes a work that uses a significant portion
  of the source files or algorithms that are included with this one.
  Specifically excluded from this are files that were generated by the software,
  or anything that is included with the software that is part of another package
  (such as files that were created or added during the 'configure' process).
  Specifically included is the use of part or all of any of the X11 workbench
  toolkit source or header files in your distributed application.  If you do not
  ship the source, the above copyright statement is still required to be placed
  in a reasonably prominent place, such as documentation, splash screens, and/or
  'about the application' dialog boxes.

  Use and distribution are in accordance with GPL, LGPL, and/or the above
  BSD-like license.  See COPYING and README files for more information.


  Additional information at http://sourceforge.net/projects/X11workbench

******************************************************************************/



#ifndef _GDB_HELPER_H_INCLUDED_
#define _GDB_HELPER_H_INCLUDED_





#endif // _GDB_HELPER_H_INCLUDED_

