//////////////////////////////////////////////////////////////////////////////
//                                                                          //
//                      _                           _                       //
//                __ _ (_) ____ ____ __ _  _ __  __| |    ___               //
//               / _` || ||_  /|_  // _` || '__|/ _` |   / __|              //
//              | (_| || | / /  / /| (_| || |  | (_| | _| (__               //
//               \__, ||_|/___|/___|\__,_||_|   \__,_|(_)\___|              //
//               |___/                                                      //
//                                                                          //
//                   project creation and other 'gizzards'                  //
//                                                                          //
//         NOTE:  'gizzard' is a combination of 'wizard' and 'gizmo'        //
//    (this is done to prevent alleging tradmark/copyright infringement)    //
//                                                                          //
//////////////////////////////////////////////////////////////////////////////

/*****************************************************************************

    X11workbench - X11 programmer's 'work bench' application and toolkit
    Copyright (c) 2010-2019 by Bob Frazier (aka 'Big Bad Bombastic Bob')
                           all rights reserved

  DISCLAIMER:  The X11workbench application and toolkit software are supplied
               'as-is', with no warranties, either implied or explicit.

  BSD-like license:

  There is no restriction as to what you can do with this software, so long
  as you include the above copyright notice and DISCLAIMER for any distributed
  work that is linked with, equivalent to, or derived from any portion of this
  software, along with this paragraph that explains the terms of the license if
  the source is also being made available.  "Linked with" includes the use of a
  portion of any of the source and/or header files, or their compiled binary
  output, as a part of your application or library.   A "derived work"
  describes a work that uses a significant portion of the source files or the
  algorithms that are included with this software.

  EXCLUSIONS

  Specifically excluded from this requirement are files that were generated by
  the software, or anything that is included with the software that is part of
  another package (such as files that were created or added during the
  'configure' process).

  DISTRIBUTION

  The license also covers the use of part or all of any of the X11 workbench
  toolkit source or header files in your distributed application, in source or
  binary form.  If you do not ship the source, the above copyright statement
  and DISCLAIMER is still required to be placed in a reasonably prominent
  place, such as documentation, splash screens, and/or 'about the application'
  dialog boxes.

  Use and distribution are in accordance with GPL, LGPL, and/or the above
  BSD-like license.  See COPYING and README.md files for more information.

  Additionally, this software, in source or binary form, and in whole or in
  part, may be used by explicit permission from the author, without the need
  of a license.

  Additional information at http://sourceforge.net/projects/X11workbench
  and http://bombasticbob.github.io/X11workbench/

******************************************************************************/

#include "X11workbench.h"
#include "gizzard.h"

//
// TENTATIVE PLANS ON APPLICATION 'Gizzards' (aka 'wizards' in case of trademarks)
//
// 1.  tab-MDI and dialog-based applications for X11 Workbench Toolkit
//
// 2.  similar to above, using a "foundation class" wrapper (C++)
//
// 3.  MDI and dialog-based applications for wxWidgets (C++)
//
// 4.  similar for GTK and/or GTK+ (C++)
//
// 5.  shared lib / DLL projects.
//     NOTE:  'dlopen' calls _init(), 'dlclose()' calls _fini() in the shared lib.
//            MS DLLs call DllMain() with DLL_PROCESS_ATTACH or DLL_PROCESS_DETACH
//            These need to be abstracted by whatever framework I use.
//     NOTE 2:  MS also calls DllMain() when starting/ending a process or thread
//              for an already-loaded DLL. See MS docs for the context and
//              implications of these calls.
//
// 6.  alternate platform application wizards (such as Arduino)
//
// 7.  possible Android application wizards (would require installing Android SDK)
//
//
// The priority, of course, is to use the X11 Workbench Toolkit.  Once it is able
// to run under windows, there will be no real need for anything else.  The next
// priority are the two toolkits that are already cross-platform, namely wxWidgets
// and GTK.  Qt is also a possibility, though it has its own (pay for) IDE already.
//
// Alternate platforms like Arduino might be helpful in that there is no existing
// 'application gizzard', and I intend to make X11workbench's IDE easier/better to
// use than the Arduino IDE.  However, without a proper debugging interface to a
// microcontroller system, it has limited added value (other than the 'gizzard').
//
//



