//////////////////////////////////////////////////////////////////////////////////////////
//  __  __ _  _                        _     _                         _         _      //
//  \ \/ // |/ |__      __ ___   _ __ | | __| |__    ___  _ __    ___ | |__     | |__   //
//   \  / | || |\ \ /\ / // _ \ | '__|| |/ /| '_ \  / _ \| '_ \  / __|| '_ \    | '_ \  //
//   /  \ | || | \ V  V /| (_) || |   |   < | |_) ||  __/| | | || (__ | | | | _ | | | | //
//  /_/\_\|_||_|  \_/\_/  \___/ |_|   |_|\_\|_.__/  \___||_| |_| \___||_| |_|(_)|_| |_| //
//                                                                                      //
//                          'main' source for X11workbench                              //
//                                                                                      //
//////////////////////////////////////////////////////////////////////////////////////////

/*****************************************************************************

    X11workbench - X11 programmer's 'work bench' application and toolkit
    Copyright (c) 2010-2018 by Bob Frazier (aka 'Big Bad Bombastic Bob')
                             all rights reserved

  DISCLAIMER:  The X11workbench application and toolkit software are supplied
               'as-is', with no waranties, either implied or explicit.

  BSD-like license:

  There is no restriction as to what you can do with this software, so long
  as you include the above copyright notice and DISCLAIMER for any distributed
  work that is equal to or derived from this one, along with this paragraph
  that explains the terms of the license if the source is also being made
  available.  A "derived work" describes a work that uses a significant portion
  of the source files or algorithms that are included with this one.
  Specifically excluded from this are files that were generated by the software,
  or anything that is included with the software that is part of another package
  (such as files that were created or added during the 'configure' process).
  Specifically included is the use of part or all of any of the X11 workbench
  toolkit source or header files in your distributed application.  If you do not
  ship the source, the above copyright statement is still required to be placed
  in a reasonably prominent place, such as documentation, splash screens, and/or
  'about the application' dialog boxes.

  Use and distribution are in accordance with GPL, LGPL, and/or the above
  BSD-like license.  See COPYING and README files for more information.


  Additional information at http://sourceforge.net/projects/X11workbench

******************************************************************************/


// common includes (this also includes 'X' headers)
#include "window_helper.h"


typedef enum __WBFILE_TYPE__
{
  WBFILE_TYPE_NONE     = 0,
  WBFILE_TYPE_TEXT     = 1,
  WBFILE_TYPE_CPROG    = 2,
  WBFILE_TYPE_CPP      = 3,
  WBFILE_TYPE_CHEADER  = 4,
  WBFILE_TYPE_MAKEFILE = 5,
  WBFILE_TYPE_AUTOCONF = 6,
  WBFILE_TYPE_RESOURCE = 7,
  WBFILE_TYPE_PIXMAP   = 8,
  WBFILE_TYPE_DIALOG   = 9,
  WBFILE_TYPE_MENU     = 10,
  WBFILE_TYPE_TOOLBAR  = 11,
  WBFILE_TYPE_SHELL    = 12,
  WBFILE_TYPE_PYTHON   = 13,
  WBFILE_TYPE_PERL     = 14,
  WBFILE_TYPE_ASM      = 15,
  WBFILE_TYPE_HTML     = 16,
  WBFILE_TYPE_XML      = 17,
  WBFILE_TYPE_JAVA     = 18,
  WBFILE_TYPE_JS       = 19,
  WBFILE_TYPE_PHP      = 20,
  WBFILE_TYPE_LAST     = 20 // update this if I add more types
} WBFILE_TYPE;


///////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                       //
//   _____        _                             _                          _      _     ____  ___        //
//  | ____|__  __| |_  ___  _ __  _ __    __ _ | | ___    __ _  _ __    __| |    / \   |  _ \|_ _| ___   //
//  |  _|  \ \/ /| __|/ _ \| '__|| '_ \  / _` || |/ __|  / _` || '_ \  / _` |   / _ \  | |_) || | / __|  //
//  | |___  >  < | |_|  __/| |   | | | || (_| || |\__ \ | (_| || | | || (_| |  / ___ \ |  __/ | | \__ \  //
//  |_____|/_/\_\ \__|\___||_|   |_| |_| \__,_||_||___/  \__,_||_| |_| \__,_| /_/   \_\|_|   |___||___/  //
//                                                                                                       //
//                                                                                                       //
///////////////////////////////////////////////////////////////////////////////////////////////////////////

// external types (prototype definitions for functions)
typedef struct __WB_FRAME_WINDOW__ WBFrameWindow; // see frame_window.h


// global variables

extern Display *display;        // X server connection
extern Window win;              // main window Window ID


// general purpose utilities to be called by external things

int DoFileOpen(WBFrameWindow *pMainFrame, const char *szFileName);
WBFILE_TYPE GetFileType(const char *szFileName);


// utilities specific to context-sensitive help

void DoContextSensitiveHelp(const char *szTerm);
int spawn_async(const char *szApp, ...);



