/////////////////////////////////////////////////////////////////////
//        _     _ _     _      __                                  //
//    ___| |__ (_) | __| |    / _|_ __ __ _ _ __ ___   ___   ___   //
//   / __| '_ \| | |/ _` |   | |_| '__/ _` | '_ ` _ \ / _ \ / __|  //
//  | (__| | | | | | (_| |   |  _| | | (_| | | | | | |  __/| (__   //
//   \___|_| |_|_|_|\__,_|___|_| |_|  \__,_|_| |_| |_|\___(_)___|  //
//                      |_____|                                    //
//                                                                 //
//        a window that exists as a tab in a frame window          //
//                                                                 //
//           (part of the 'frame window' support API)              //
//                                                                 //
/////////////////////////////////////////////////////////////////////

/*****************************************************************************

    X11workbench - X11 programmer's 'work bench' application and toolkit
    Copyright (c) 2010-2016 by Bob Frazier (aka 'Big Bad Bombastic Bob')
                             all rights reserved

  DISCLAIMER:  The X11workbench application and toolkit software are supplied
               'as-is', with no waranties, either implied or explicit.

  BSD-like license:

  There is no restriction as to what you can do with this software, so long
  as you include the above copyright notice and DISCLAIMER for any distributed
  work that is equal to or derived from this one, along with this paragraph
  that explains the terms of the license if the source is also being made
  available.  A "derived work" describes a work that uses a significant portion
  of the source files or algorithms that are included with this one.
  Specifically excluded from this are files that were generated by the software,
  or anything that is included with the software that is part of another package
  (such as files that were created or added during the 'configure' process).
  Specifically included is the use of part or all of any of the X11 workbench
  toolkit source or header files in your distributed application.  If you do not
  ship the source, the above copyright statement is still required to be placed
  in a reasonably prominent place, such as documentation, splash screens, and/or
  'about the application' dialog boxes.

  Use and distribution are in accordance with GPL, LGPL, and/or the above
  BSD-like license.  See COPYING and README files for more information.


  Additional information at http://sourceforge.net/projects/X11workbench

******************************************************************************/


#include <stdlib.h>
#include <unistd.h>
#include <memory.h>
#include <string.h>
#include <strings.h>

#include "window_helper.h"
#include "font_helper.h"
#include "child_frame.h"
#include "draw_text.h"


static WBChildFrame *pChildFrames = NULL;  // pointer to linked list of 'Child Frame' windows


int FWInitChildFrame(WBChildFrame *pChildFrame, WBFrameWindow *pOwner, XFontStruct *pFont,
                     const char *szFocusMenu, const WBFWMenuHandler *pHandlerArray,
                     WBWinEvent pUserCallback, int fFlags)
{
WBChildFrame *pC;
XSetWindowAttributes xswa;  /* Temporary Set Window Attribute struct */
Display *pDisplay = WBGetDefaultDisplay();
int iRval = -1;


  if(!pChildFrame || !pOwner || pOwner->wID == None)
  {
    // TODO:  validate 'pOwner' as a valid WBFrameWindow ??  

    WB_ERROR_PRINT("%s - invalid pointers or owner window does not exist\n", __FUNCTION__);

    return -1;
  }

  // zero out entire structure beforehand
  bzero(pChildFrame, sizeof(*pChildFrame));


  // FIRST, attach the child frame to my list o' child frames, making sure
  // that it is not already there [if it is assume this was called twice]
  // while I'm at it, zero out the structure BEFORE I assign 'pNext'

  if(!pChildFrames)
  {
    pChildFrames = pChildFrame;
    pChildFrame->pNext = NULL; // make sure
  }
  else
  {
    pC = pChildFrames;

    while(pC->pNext)
    {
      if(pC == pChildFrame) // just in case
      {
        WB_ERROR_PRINT("%s - unexpected error condition, did you call this function before?\n", __FUNCTION__);

        return -2;
      }

      pC = pC->pNext;
    }

    if(pC)
    {
      // zero out entire structure beforehand
      bzero(pChildFrame, sizeof(*pChildFrame));

      pC->pNext = pChildFrame;
      pChildFrame->pNext = NULL;
    }
    else
    {
      // internal error, flag it for now and return "fail"
      WB_ERROR_PRINT("%s - unexpected condition, returning error\n", __FUNCTION__);

      return -3;
    }
  }

  // if the owner is valid, but NOT tabbed, and it already has
  // a WBChildFrame, then I fail to create this one.

  if((WBFrameWindow_NO_TABS & pOwner->iFlags)) // window has NO tabs
  {
    if(FWGetNumContWindows(pOwner)) // error *OR* > 0, doesn't matter, can ONLY have one tab in the frame
    {
      FWDestroyChildFrame(pChildFrame); // this unhooks everything (alloc'd things are zero'd by bzero)

      return -4; // can't create, SDI
    }
  }


  // NEXT, set up all of the various 'things' in the structure that are simple assignments
  pChildFrame->ulTag = CHILD_FRAME_TAG;
  pChildFrame->destructor = NULL; // make sure

  if(!pFont)
  {
    pChildFrame->pFont = NULL;
  }
  else
  {
    pChildFrame->pFont = WBCopyFont(pFont);
  }

  if(szFocusMenu)
  {
    pChildFrame->pszMenuResource = WBCopyString(szFocusMenu);

    if(!pChildFrame->pszMenuResource)
    {
      FWDestroyChildFrame(pChildFrame); // this unhooks everything (alloc'd things are zero'd by bzero)
      return -5; // not enough memory
    }
  }
  else
  {
    pChildFrame->pszMenuResource = NULL;
  }

  if(pHandlerArray)
  {
    const WBFWMenuHandler *pH;
    int i1;

    // count the number of entries in the menu handler
    for(i1=0, pH = pHandlerArray; pH->lMenuID || pH->callback || pH->UIcallback; i1++, pH++)
    {
      // NOTHING inside the loop.  just count.
    }

    // allocate space and make a copy

    pChildFrame->pMenuHandler = (WBFWMenuHandler *)malloc(sizeof(WBFWMenuHandler) * (i1 + 2));

    if(pChildFrame->pMenuHandler)
    {
      memcpy(pChildFrame->pMenuHandler, pHandlerArray,
             sizeof(WBFWMenuHandler) * (i1 + 1));
    }
    else
    {
      FWDestroyChildFrame(pChildFrame); // this unhooks everything (alloc'd things are zero'd by bzero)
      return -5; // not enough memory
    }
  }

  // Next, I need to create the window via 'WBCreateWindow()'

  bzero(&xswa, sizeof(xswa));

  xswa.border_pixel = FWGetDefaultBD().pixel;
  xswa.background_pixel = FWGetDefaultBG().pixel;  // typically a 'grey' color
  xswa.colormap = DefaultColormap(pDisplay, DefaultScreen(pDisplay));
  xswa.bit_gravity = CenterGravity;

  pChildFrame->wID = WBCreateWindow(pDisplay, pOwner->wID, FWChildFrameEvent, "ChildFrame",
                                    pOwner->iClientX, pOwner->iClientY,
                                    pOwner->iClientWidth - 2, pOwner->iClientHeight - 2, // border is 1 pixel, so subtract 2
                                    1, InputOutput,
                                    CWBorderPixel | CWBackPixel | CWColormap | CWBitGravity,
                                    &xswa);

  if(pChildFrame->wID == None)
  {
    FWDestroyChildFrame(pChildFrame);
    return -6; // could not create the window
  }

  // immediately identify this window's data struct using window data
  WBSetWindowData(pChildFrame->wID, 0, (void *)pChildFrame); // window data is pointer to this struct
  pChildFrame->pUserCallback = pUserCallback;


  // create the default graphics context using the frame's color info
  WBCreateWindowDefaultGC(pChildFrame->wID, FWGetDefaultFG().pixel, FWGetDefaultBG().pixel);

  // now allow specific kinds of input messages.  I won't need 'structure notify' as they won't work
  // anyway.  those end up going to the frame window, and it passes them (as needed) to me.
  XSelectInput(pDisplay, pChildFrame->wID,
               WB_STANDARD_INPUT_MASK | WB_MOUSE_INPUT_MASK | WB_KEYBOARD_INPUT_MASK);


  // FINALLY, inform the frame window, which will set up some other stuff for me

  pChildFrame->pOwner = pOwner;
  iRval = FWAddContainedWindow(pOwner, pChildFrame); // TODO:  make THIS assign the owner pointer?

  if(iRval < 0) // error? (returns negative on error, otherwise the tab index)
  {
    FWDestroyChildFrame(pChildFrame); // this frees up all of the resources (but does not free the mem block)
  }

  // TODO:  other things

  return iRval;
}

void FWDestroyChildFrame(WBChildFrame *pChildFrame)
{
WBChildFrame *pC, *pC2;
Window wID;


  if(!pChildFrame)
  {
    return;
  }

  wID = pChildFrame->wID; // make a copy of it

  // FIRST, tell the owner to remove me from the list

  if(pChildFrame->pOwner)
  {
    FWRemoveContainedWindow(pChildFrame->pOwner, pChildFrame);

    if(pChildFrame->pOwner != NULL)
    {
      WB_ERROR_PRINT("ERROR:  %s - owner pointer was nut 'NULL'd out\n", __FUNCTION__);
    }

    pChildFrame->pOwner = NULL;
  }

  // NOW, free up any resources that were malloc'd - they must also be free'd

  if(pChildFrame->szDisplayName)
  {
    free(pChildFrame->szDisplayName);
    pChildFrame->szDisplayName = NULL;
  }

  if(pChildFrame->pFont)
  {
    XFreeFont(WBGetDefaultDisplay(), pChildFrame->pFont);
    pChildFrame->pFont = NULL;
  }

  if(pChildFrame->pMenuHandler)
  {
    free(pChildFrame->pMenuHandler);
    pChildFrame->pMenuHandler = NULL;
  }

  if(pChildFrame->pszMenuResource)
  {
    free(pChildFrame->pszMenuResource);
    pChildFrame->pszMenuResource = NULL;
  }

  // And, NOW, destroy the window itself [if it's valid]
  //
  // NOTE:  to prevent recursion problems, a 'DestroyNotify' would mark the window ID 'None'
  //        before calling this function.  this will happen within my OWN proc, if the superclass doesn't do it

  if(pChildFrame->wID != None) // if there's a chance of recursion, I detect it here
  {
    WBDestroyWindow(pChildFrame->wID);
    pChildFrame->wID = None; // make sure
  }

  // FINALLY, unlink this object from the child frame list.  Do it by walking the list, looking for
  // this entry in the list.  If I find it, I unlink it [otherwise, the 'pNext' link might be *stale*]

  if(pChildFrames) // just in case, walk the list - do not rely on possibly stale pointers
  {
    pC2 = NULL;
    pC = pChildFrames;

    while(pC)
    {
      if(pC == pChildFrame) // just in case
      {
        if(pC2)
        {
          pC2->pNext = pC->pNext; // remove from link list
        }
        else
        {
          pChildFrames = pC->pNext; // it was the head of the chain
        }

        pC->pNext = NULL;

        break;
      }

      pC2 = pC;
      pC = pC->pNext;
    }
  }

  pChildFrame->pNext = NULL; // make sure it's not a pointer someplace that can cause problems

  // if the 'superclass' destructor was specified, call it NOW.
  
  if(pChildFrame->destructor)
  {
    // at this point, we ALWAYS destroy the callback function.
    // "it is assumed" that I won't be needing 'DestroyNotify' to
    // trigger any destruction.  That happens *AFTER* the window was
    // destroyed, and happens asynchronously, typically before the
    // frame window was destroyed.

    // so, to make sure that I don't get an event callback that references
    // the window object after it's free'd, I need to remove the callback.

    if(wID != None)
    {
      WBUnregisterWindowCallback(wID); // no more event handling
      WBSetWindowData(wID, 0, (void *)NULL); // window data is no longer pointing here
    }

    // and THEN, it's safe to call the destructor on the original object.
    pChildFrame->destructor(pChildFrame); // this should auto-delete as well
  }
  else
  {
    // TODO:  should I perform a 'Destroy Notify' callback of my own?

    // NOTE:  NOT calling 'WBunregisterWindowCallback()' so 'Destroy Notify' does its job.  hopefully.
  }

  // NOTE:  I have to leave the tag alone at this point, to validate that it's
  //        a 'Child Frame' structure.  But everything else needs to be zero'd out
  //        (I used to use 'bzero' but I'm just commenting it here, for reference)
  //        so... make sure everything that's free'd gets ZERO'd as well.  this is
  //        because a 'DestroyNotify' handler that frees up the memory (and destroys
  //        any 'superclass') will probably call this function again, and it might
  //        happen asynchronously.  In fact, it probably WILL happen asynchronously.

  //  bzero(pChildFrame, sizeof(*pChildFrame)); // zero it out (as a matter of course)

  // note that I do *NOT* free the WBChildFrame HERE - this simply releases all resources for it.
  // If there is NO DESTRUCTOR, the 'Destroy Notify' handler needs to do that, or at least SOMETHING.
  // *NOT* handling this properly can result in 'use after free' problems.
}

void FWSetChildFrameMenu(WBChildFrame *pChildFrame, const char *szFocusMenu)
{
  if(!pChildFrame || pChildFrame->ulTag != CHILD_FRAME_TAG)
  {
    return;
  }

  if(pChildFrame->pszMenuResource)
  {
    free(pChildFrame->pszMenuResource);
  }

  if(szFocusMenu)
  {
    pChildFrame->pszMenuResource = WBCopyString(szFocusMenu);
  }
  else
  {
    pChildFrame->pszMenuResource = NULL;
  }

}

void FWSetChildFrameMenuHandlers(WBChildFrame *pChildFrame, const WBFWMenuHandler *pHandlerArray)
{
  if(!pChildFrame || pChildFrame->ulTag != CHILD_FRAME_TAG)
  {
    return;
  }

  if(pChildFrame->pMenuHandler)
  {
    free(pChildFrame->pMenuHandler);
  }

  if(pHandlerArray)
  {
    const WBFWMenuHandler *pH;
    int i1;

    // count the number of entries in the menu handler
    for(i1=0, pH = pHandlerArray; pH->lMenuID || pH->callback || pH->UIcallback; i1++, pH++)
    {
      // NOTHING inside the loop.  just count.
    }

    // allocate space and make a copy

    pChildFrame->pMenuHandler = (WBFWMenuHandler *)malloc(sizeof(WBFWMenuHandler) * (i1 + 2));

    if(pChildFrame->pMenuHandler)
    {
      memcpy(pChildFrame->pMenuHandler, pHandlerArray,
             sizeof(WBFWMenuHandler) * (i1 + 1));
    }
  }
  else
  {
    pChildFrame->pMenuHandler = NULL;
  }
}

void FWSetChildFrameDisplayName(WBChildFrame *pChildFrame, const char *szDisplayName)
{
  if(!pChildFrame || pChildFrame->ulTag != CHILD_FRAME_TAG)
  {
    return;
  }

  if(pChildFrame->szDisplayName)
  {
    free(pChildFrame->szDisplayName);
  }

  if(!szDisplayName)
  {
    return;
  }

  pChildFrame->szDisplayName = WBCopyString(szDisplayName);
}

void FWSetChildFrameImageAtom(WBChildFrame *pChildFrame, Atom aImage)
{
  if(!pChildFrame || pChildFrame->ulTag != CHILD_FRAME_TAG)
  {
    return;
  }

  pChildFrame->aImageAtom = aImage;
}

void FWSetChildFrameExtent(WBChildFrame *pChildFrame, int iXExtent, int iYExtent)
{
  if(!pChildFrame || pChildFrame->ulTag != CHILD_FRAME_TAG)
  {
    return;
  }

  // NOTE:  see (and maybe call) FWChildFrameRecalcLayout, below
}


void FWChildFrameRecalcLayout(WBChildFrame *pChildFrame)
{
WBFrameWindow *pOwner;
Display *pDisplay;
int iL, iT, iW, iH;


  if(!pChildFrame || pChildFrame->ulTag != CHILD_FRAME_TAG)
  {
    return;
  }


  pDisplay = WBGetWindowDisplay(pChildFrame->wID);
  pOwner = pChildFrame->pOwner;

  if(!pOwner) // irrelevant if NULL.  TODO:  properly validate this (anal retentive if DEBUG build)
  {
    return;
  }

  iL = pOwner->iClientX;
  iT = pOwner->iClientY;
  iW = pOwner->iClientWidth;
  iH = pOwner->iClientHeight;

// re-calculate these members of the WBChildFrame structure, as needed

//  pChildFrame->iLeft = iL converted to correct units and scrolled;
//  pChildFrame->iTop = iT converted to correct units and scrolled;  
//  pChildRrame->iWidth = iW converted to correct units;
//  pChildFrame->iHeight = iH converted to correct units;
    



  // TODO:  anything ELSE that I need to do when re-calculating the layout, scrollbars, whatever
  //        just apply that to iL, iT, iW, iH so that it reflects the correct viewpoirt in pixels
  //        minus any border, decorations, scrollbars, whatever, with 0,0 being top,left


  // resize the window accordingly
  XMoveWindow(pDisplay, pChildFrame->wID, iL, iT);
  XResizeWindow(pDisplay, pChildFrame->wID, iW - 2, iH - 2); // 1 pixel for border

  // NOW, tell the user callback function (if any) what's happening.
  // I must assume that the owning frame is valid and has already re-calc'd its layout

  if(pChildFrame->pUserCallback)
  {
    Display *pDisplay;
    XClientMessageEvent evt;

    pDisplay = WBGetWindowDisplay(pChildFrame->wID);

    bzero(&evt, sizeof(evt));
    evt.type = ClientMessage;

    evt.display = pDisplay;
    evt.window = pChildFrame->wID;
    evt.message_type = aRESIZE_NOTIFY;
    evt.format = 32;  // always
    evt.data.l[0] = iL;
    evt.data.l[1] = iT;
    evt.data.l[2] = iL + iW; // right
    evt.data.l[3] = iT + iH; // bottom

    pChildFrame->pUserCallback(evt.window, (XEvent *)&evt);
  }  
}


int FWChildFrameQueryClose(WBChildFrame *pChildFrame)
{
Display *pDisplay;
XClientMessageEvent evt;


  if(!pChildFrame || pChildFrame->ulTag != CHILD_FRAME_TAG)
  {
    return -1; // an error
  }

  if(!pChildFrame->pUserCallback)
  {
    return 0; // return 'ok to close' when there's no 'user callback' function to query
  }

  pDisplay = WBGetWindowDisplay(pChildFrame->wID);

  bzero(&evt, sizeof(evt));
  evt.type = ClientMessage;

  evt.display = pDisplay;
  evt.window = pChildFrame->wID;
  evt.message_type = aQUERY_CLOSE;
  evt.format = 32;  // always

  return pChildFrame->pUserCallback(evt.window, (XEvent *)&evt);
}


// DEFAULT WINDOW EVENT HANDLER FOR CHILD FRAME

int FWChildFrameEvent(Window wID, XEvent *pEvent)
{
int iRval = 0;
WBChildFrame *pC;
WBFrameWindow *pFW;
#ifndef NO_DEBUG
char tbuf[32]; // for keyboard input
int nChar = sizeof(tbuf);
#endif // NO_DEBUG


  pC = FWGetChildFrameStruct(wID);

  if(!pC)
  {
#ifndef NO_DEBUG
    WB_ERROR_PRINT("ERROR:  %s - no child frame structure, window data is %p\n", __FUNCTION__, WBGetWindowData(wID, 0));

    WBDebugDumpEvent(pEvent);
#endif // NO_DEBUG

    return 0;
  }

  pFW = pC->pOwner; // make sure I know my owning frame window


  // TODO:  messages I handle myself, before any user callbacks
  //        (and perhaps messages that I don't pass to the callback at all)

  if(pC->pUserCallback)
  {
    iRval = pC->pUserCallback(wID, pEvent);
  }  

  // regardless, for a 'DestroyNotify, assign wID to 'None' in the ChildFrame class

  if(!iRval)
  {
    // TODO:  default handling of messages NOT handled by user callback

    switch(pEvent->type)
    {
      case KeyPress:
        {
#ifndef NO_DEBUG
          int iACS = 0;
          int iKey = WBKeyEventProcessKey((XKeyEvent *)pEvent, tbuf, &nChar, &iACS);

          WB_DEBUG_PRINT(DebugLevel_Heavy | DebugSubSystem_Event | DebugSubSystem_Frame | DebugSubSystem_Keyboard,
                         "%s KEY PRESS for KEY %d KEYCODE %d MASK=%d (%xH)\n",
                           __FUNCTION__, iKey, ((XKeyEvent *)pEvent)->keycode,
                           ((XKeyEvent *)pEvent)->state, ((XKeyEvent *)pEvent)->state);
#endif // NO_DEBUG

          // check for menu and hotkey activation.
//          if(nChar > 0) // only for "real" characters (i.e. not just the ALT key)
          if(pFW)
          {
            WBMenuBarWindow *pMenuBar = MBGetMenuBarWindowStruct(WBGetMenuWindow(pFW->wID));

            if(pMenuBar)  // menu bar exists?
            {
              WB_DEBUG_PRINT(DebugLevel_Excessive | DebugSubSystem_Menu | DebugSubSystem_Frame | DebugSubSystem_Keyboard,
                             "%s call to MBMenuProcessHotKey for menu window %d (%08xH)\n",
                             __FUNCTION__, (int)pMenuBar->wSelf, (int)pMenuBar->wSelf);

              iRval = MBMenuProcessHotKey(pMenuBar->pMenu, (XKeyEvent *)pEvent);
            }
          }
        }
        break;

      case KeyRelease:
        {
          // KeyRelease
#ifndef NO_DEBUG
          int iACS = 0, iKey = WBKeyEventProcessKey((XKeyEvent *)pEvent, tbuf, &nChar, &iACS);

          if(nChar > 0)
          {
            WB_DEBUG_PRINT(DebugLevel_Heavy | DebugSubSystem_Event | DebugSubSystem_Frame | DebugSubSystem_Keyboard,
                           "%s KEY RELEASE for KEY %d KEYCODE %d  MASK=%d (%xH)\n",
                           __FUNCTION__, iKey, ((XKeyEvent *)pEvent)->keycode,
                           ((XKeyEvent *)pEvent)->state, ((XKeyEvent *)pEvent)->state);

          }
#endif // NO_DEBUG

        }

        break;
    }
  }


  if(pEvent->type == DestroyNotify &&
     pEvent->xdestroywindow.window == wID)
  {
    WB_DEBUG_PRINT(DebugLevel_Heavy | DebugSubSystem_Event | DebugSubSystem_Frame,
                   "%s - DestroyNotify\n", __FUNCTION__);

    if(!iRval)
    {
      WB_ERROR_PRINT("TEMPORARY:  %s - DestroyNotify *NOT* handled by superclass\n", __FUNCTION__);
    }

    pC = FWGetChildFrameStruct(wID); // re-get the structure (it may have been deleted, probably SHOULD have been)

    if(pC && pC->wID != None) // haven't called FWDestroyChildFrame yet?
    {
      // mark window ID 'None', then call FWDestroyChildFrame from here
      // by design it's safe to do that...

      pC->wID = None; // since window already 'destroyed' - I'm getting the notification after all

      // set the window callback to NULL - this disconnects me from the message processor also
      // as well as freeing up everything

      FWDestroyChildFrame(pC); // make sure it's destroyed, unlinked, etc. (pointer may not be valid now)

      WB_ERROR_PRINT("TEMPORARY:  %s - DestroyNotify handled by Child Window base class\n", __FUNCTION__);
    }

    WBUnregisterWindowCallback(wID); // prevents any more messages from being dispatched to this function

    WB_DEBUG_PRINT(DebugLevel_ERROR/*DebugLevel_Verbose | DebugSubSystem_Event | DebugSubSystem_Frame*/,
                   "%s - child frame window destroyed\n", __FUNCTION__);
    return 1;
  }


  return iRval;
}



