//////////////////////////////////////////////////////////////////////////////////////////
//                  _  _  _                 _             _                             //
//         ___   __| |(_)| |_    __      __(_) _ __    __| |  ___ __      __  ___       //
//        / _ \ / _` || || __|   \ \ /\ / /| || '_ \  / _` | / _ \\ \ /\ / / / __|      //
//       |  __/| (_| || || |_     \ V  V / | || | | || (_| || (_) |\ V  V /_| (__       //
//        \___| \__,_||_| \__|_____\_/\_/  |_||_| |_| \__,_| \___/  \_/\_/(_)\___|      //
//                           |_____|                                                    //
//                                                                                      //
//                     a window into which you can type text                            //
//                                                                                      //
//////////////////////////////////////////////////////////////////////////////////////////

/*****************************************************************************

    X11workbench - X11 programmer's 'work bench' application and toolkit
    Copyright (c) 2010-2016 by Bob Frazier (aka 'Big Bad Bombastic Bob')
                             all rights reserved

  DISCLAIMER:  The X11workbench application and toolkit software are supplied
               'as-is', with no waranties, either implied or explicit.

  BSD-like license:

  There is no restriction as to what you can do with this software, so long
  as you include the above copyright notice and DISCLAIMER for any distributed
  work that is equal to or derived from this one, along with this paragraph
  that explains the terms of the license if the source is also being made
  available.  A "derived work" describes a work that uses a significant portion
  of the source files or algorithms that are included with this one.
  Specifically excluded from this are files that were generated by the software,
  or anything that is included with the software that is part of another package
  (such as files that were created or added during the 'configure' process).
  Specifically included is the use of part or all of any of the X11 workbench
  toolkit source or header files in your distributed application.  If you do not
  ship the source, the above copyright statement is still required to be placed
  in a reasonably prominent place, such as documentation, splash screens, and/or
  'about the application' dialog boxes.

  Use and distribution are in accordance with GPL, LGPL, and/or the above
  BSD-like license.  See COPYING and README files for more information.


  Additional information at http://sourceforge.net/projects/X11workbench

******************************************************************************/


#include <stdlib.h>
#include <unistd.h>
#include <memory.h>
#include <string.h>
#include <strings.h>

#include "window_helper.h"
#include "edit_window.h"


int FWEditWindowEvent(Window wID, XEvent *pEvent);



WBEditWindow *WBCreateEditWindow(WBFrameWindow *pOwner, XFontStruct *pFont,
                                 const char *szFocusMenu, const WBFWMenuHandler *pHandlerArray,
                                 int fFlags)
{
WBEditWindow *pRval;

  pRval = (WBEditWindow *)malloc(sizeof(*pRval));

  if(!pRval)
  {
    WB_ERROR_PRINT("ERROR:  %s - not enough memory\n", __FUNCTION__);
    return NULL;
  }

  bzero(pRval, sizeof(*pRval));

  pRval->szFileName = NULL;  // explicitly do this, though the bzero would've
  pRval->nTextObjects = 0;
  pRval->nMaxTextObjects = 0;
  pRval->pTextObjects = NULL;


  if(0 > FWInitChildFrame(&(pRval->childframe), pOwner, pFont, szFocusMenu, pHandlerArray,
                          FWEditWindowEvent, fFlags))
  {
    WB_ERROR_PRINT("ERROR:  %s - unable to initialize child frame\n", __FUNCTION__);

    free(pRval);

    return NULL;
  }                    

  // TODO:  any other initialization

  return pRval;
}

void WBDestroyEditWindow(WBEditWindow *pEditWindow)
{
  FWDestroyChildFrame(&(pEditWindow->childframe));

  if(pEditWindow->szFileName)
  {
    free(pEditWindow->szFileName);
    pEditWindow->szFileName = NULL;
  }
  if(pEditWindow->pTextObjects)
  {
    // TODO:  destroy them individually

    free(pEditWindow->pTextObjects);
    pEditWindow->pTextObjects = NULL;
  }

  free(pEditWindow); // TODO:  put this in a 'garbage collector' instead?
}

WBEditWindow *WBEditWindowFromWindowID(Window wID)
{
  return (WBEditWindow *)FWGetChildFrameStruct(wID); // for now; later, use a tag to verify
}

int FWEditWindowEvent(Window wID, XEvent *pEvent)
{
  return 0; // for now, NONE are handled
}

